In [2]:
# Import dependencies
import numpy as np
import pandas as pd
from time import time
from IPython.display import display
#import seaborn

# Pretty display for notebooks
%matplotlib inline

In [3]:
# Load the Census dataset
data = pd.read_csv("census_cleaned.csv")

# Success - Display the first record
display(data.head(n=5))
#display(data['education-num'].unique())

,age,workclass,education_level,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,0,2174,0,40,United-States,0
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,0,0,0,13,United-States,0
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,0,0,0,40,United-States,0
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,0,0,0,40,United-States,0
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,1,0,0,40,Cuba,0

In [4]:
# Drop any rows that have Nan values (how: drop whole row)
data.dropna(how='all')

,age,workclass,education_level,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,0,2174,0,40,United-States,0
1,50,Self-emp-not-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,0,0,0,13,United-States,0
2,38,Private,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,0,0,0,40,United-States,0
3,53,Private,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,0,0,0,40,United-States,0
4,28,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,1,0,0,40,Cuba,0
5,37,Private,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,1,0,0,40,United-States,0
6,49,Private,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,1,0,0,16,Jamaica,0
7,52,Self-emp-not-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,0,0,0,45,United-States,1
8,31,Private,Masters,14,Never-married,Prof-specialty,Not-in-family,White,1,14084,0,50,United-States,1
9,42,Private,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,0,5178,0,40,United-States,1
10,37,Private,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,0,0,0,80,United-States,1
11,30,State-gov,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,0,0,0,40,India,1
12,23,Private,Bachelors,13,Never-married,Adm-clerical,Own-child,White,1,0,0,30,United-States,0
13,32,Private,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,0,0,0,50,United-States,0
14,34,Private,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,0,0,0,45,Mexico,0
15,25,Self-emp-not-inc,HS-grad,9,Never-married,Farming-fishing,Own-child,White,0,0,0,35,United-States,0
16,32,Private,HS-grad,9,Never-married,Machine-op-inspct,Unmarried,White,0,0,0,40,United-States,0
17,38,Private,11th,7,Married-civ-spouse,Sales,Husband,White,0,0,0,50,United-States,0
18,43,Self-emp-not-inc,Masters,14,Divorced,Exec-managerial,Unmarried,White,1,0,0,45,United-States,1
19,40,Private,Doctorate,16,Married-civ-spouse,Prof-specialty,Husband,White,0,0,0,60,United-States,1
20,54,Private,HS-grad,9,Separated,Other-service,Unmarried,Black,1,0,0,20,United-States,0
21,35,Federal-gov,9th,5,Married-civ-spouse,Farming-fishing,Husband,Black,0,0,0,40,United-States,0
22,43,Private,11th,7,Married-civ-spouse,Transport-moving,Husband,White,0,0,2042,40,United-States,0
23,59,Private,HS-grad,9,Divorced,Tech-support,Unmarried,White,1,0,0,40,United-States,0
24,56,Local-gov,Bachelors,13,Married-civ-spouse,Tech-support,Husband,White,0,0,0,40,United-States,1
25,19,Private,HS-grad,9,Never-married,Craft-repair,Own-child,White,0,0,0,40,United-States,0
26,39,Private,HS-grad,9,Divorced,Exec-managerial,Not-in-family,White,0,0,0,80,United-States,0
27,49,Private,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,0,0,0,40,United-States,0
28,23,Local-gov,Assoc-acdm,12,Never-married,Protective-serv,Not-in-family,White,0,0,0,52,United-States,0
29,20,Private,Some-college,10,Never-married,Sales,Own-child,Black,0,0,0,44,United-States,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45192,25,Private,HS-grad,9,Divorced,Machine-op-inspct,Not-in-family,Black,0,0,0,40,United-States,0
45193,31,Private,HS-grad,9,Never-married,Machine-op-inspct,Not-in-family,White,0,0,0,40,United-States,0
45194,49,Self-emp-inc,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,0,0,0,40,Canada,1
45195,60,Private,Assoc-voc,11,Married-civ-spouse,Prof-specialty,Husband,White,0,7688,0,40,United-States,1
45196,39,Private,Bachelors,13,Never-married,Tech-support,Not-in-family,White,1,0,1669,40,United-States,0
45197,38,Private,Masters,14,Married-civ-spouse,Prof-specialty,Husband,White,0,0,0,50,United-States,1
45198,43,Local-gov,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,0,0,1902,50,United-States,1
45199,23,Private,HS-grad,9,Never-married,Machine-op-inspct,Own-child,White,0,0,0,40,United-States,0
45200,73,Self-emp-inc,Some-college,10,Divorced,Exec-managerial,Not-in-family,White,1,0,0,40,United-States,0
45201,35,Private,Some-college,10,Married-civ-spouse,Protective-serv,Husband,White,0,0,0,40,United-States,0
45202,66,Private,HS-grad,9,Widowed,Sales,Other-relative,White,1,0,0,8,United-States,0
45203,27,Private,Some-college,10,Never-married,Sales,Not-in-family,White,1,0,0,45,United-States,0
45204,40,Private,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,0,15024,0,55,United-States,1
45205,51,Private,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,0,0,0,40,United-States,0
45206,22,Private,Some-college,10,Never-married,Craft-repair,Own-child,White,0,0,0,40,United-States,0
45207,64,Self-emp-not-inc,HS-grad,9,Widowed,Farming-fishing,Not-in-family,White,0,0,0,32,United-States,0
45208,55,Private,HS-grad,9,Separated,Priv-house-serv,Not-in-family,White,1,0,0,32,United-States,0
45209,38,Private,Assoc-voc,11,Never-married,Adm-clerical,Unmarried,Black,1,0,0,40,United-States,0
45210,58,Private,Assoc-acdm,12,Divorced,Prof-specialty,Not-in-family,White,0,0,0,36,United-States,0
45211,32,Private,HS-grad,9,Married-civ-spouse,Handlers-cleaners,Husband,White,0,0,0,40,United-States,0
45212,48,Private,HS-grad,9,Married-civ-spouse,Adm-clerical,Husband,White,0,0,0,40,United-States,0
45213,61,Private,HS-grad,9,Married-civ-spouse,Sales,Husband,White,0,0,0,48,United-States,0
45214,31,Private,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,White,0,0,0,40,United-States,0
45215,25,Private,HS-grad,9,Never-married,Other-service,Own-child,White,1,0,0,40,United-States,0
45216,48,Local-gov,Masters,14,Divorced,Other-service,Not-in-family,White,0,0,0,40,United-States,0
45217,33,Private,Bachelors,13,Never-married,Prof-specialty,Own-child,White,0,0,0,40,United-States,0
45218,39,Private,Bachelors,13,Divorced,Prof-specialty,Not-in-family,White,1,0,0,36,United-States,0
45219,38,Private,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,White,0,0,0,50,United-States,0
45220,44,Private,Bachelors,13,Divorced,Adm-clerical,Own-child,Asian-Pac-Islander,0,5455,0,40,United-States,0
45221,35,Self-emp-inc,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,0,0,0,60,United-States,1

In [6]:
# Load the Census dataset
test = pd.read_csv("test_census_cleaned.csv")

# Success - Display the first record
display(test.head(n=5))

,Unnamed: 0,age,workclass,education_level,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,0,21.0,Private,10th,6.0,Married-civ-spouse,Craft-repair,Husband,White,0.0,0.0,0.0,40.0,United-States
1,1,49.0,Private,Bachelors,13.0,Married-civ-spouse,Adm-clerical,Wife,White,1.0,0.0,0.0,40.0,United-States
2,2,44.0,Self-emp-not-inc,Assoc-acdm,12.0,Married-civ-spouse,Other-service,Wife,White,1.0,0.0,0.0,99.0,United-States
3,3,34.0,Private,Bachelors,13.0,Married-civ-spouse,Sales,Husband,White,0.0,7298.0,0.0,46.0,United-States
4,4,24.0,Private,HS-grad,9.0,Married-civ-spouse,Machine-op-inspct,Husband,White,0.0,0.0,0.0,40.0,United-States

In [23]:
# Drop any rows that have Nan values (how: drop whole row)
test.dropna(how='all')

,Unnamed: 0,age,workclass,education_level,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country
0,0,21.0,Private,10th,6.0,Married-civ-spouse,Craft-repair,Husband,White,0.0,0.0,0.0,40.0,United-States
1,1,49.0,Private,Bachelors,13.0,Married-civ-spouse,Adm-clerical,Wife,White,1.0,0.0,0.0,40.0,United-States
2,2,44.0,Self-emp-not-inc,Assoc-acdm,12.0,Married-civ-spouse,Other-service,Wife,White,1.0,0.0,0.0,99.0,United-States
3,3,34.0,Private,Bachelors,13.0,Married-civ-spouse,Sales,Husband,White,0.0,7298.0,0.0,46.0,United-States
4,4,24.0,Private,HS-grad,9.0,Married-civ-spouse,Machine-op-inspct,Husband,White,0.0,0.0,0.0,40.0,United-States
5,5,52.0,Private,7th-8th,4.0,Divorced,Priv-house-serv,Own-child,Black,1.0,0.0,0.0,16.0,United-States
6,6,61.0,Private,7th-8th,4.0,Married-civ-spouse,Transport-moving,Husband,White,0.0,0.0,0.0,50.0,United-States
7,7,24.0,Private,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,0.0,0.0,0.0,40.0,United-States
8,8,30.0,Private,HS-grad,9.0,Never-married,Handlers-cleaners,Not-in-family,White,0.0,0.0,0.0,22.0,United-States
9,9,42.0,Local-gov,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,0.0,0.0,0.0,60.0,United-States
10,10,47.0,Local-gov,Prof-school,15.0,Married-civ-spouse,Prof-specialty,Husband,White,0.0,0.0,0.0,35.0,United-States
11,11,42.0,Self-emp-not-inc,Bachelors,13.0,Married-civ-spouse,Craft-repair,Husband,White,0.0,15024.0,0.0,60.0,United-States
12,12,58.0,Self-emp-inc,HS-grad,9.0,Married-civ-spouse,Exec-managerial,Husband,White,0.0,0.0,0.0,40.0,United-States
13,13,28.0,Self-emp-not-inc,Some-college,10.0,Never-married,Prof-specialty,Own-child,White,0.0,0.0,0.0,30.0,United-States
14,14,30.0,Self-emp-inc,Bachelors,13.0,Married-civ-spouse,Sales,Husband,White,0.0,0.0,0.0,52.0,United-States
15,15,48.0,Local-gov,Masters,14.0,Married-civ-spouse,Prof-specialty,Husband,White,0.0,0.0,0.0,40.0,United-States
16,16,55.0,Private,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,0.0,0.0,0.0,40.0,United-States
17,17,47.0,Private,Some-college,10.0,Divorced,Adm-clerical,Unmarried,White,1.0,0.0,0.0,42.0,United-States
18,18,41.0,Private,Some-college,10.0,Separated,Adm-clerical,Not-in-family,White,1.0,0.0,0.0,38.0,United-States
19,19,20.0,Self-emp-not-inc,HS-grad,9.0,Never-married,Farming-fishing,Own-child,White,0.0,0.0,0.0,40.0,United-States
20,20,21.0,Private,Some-college,10.0,Never-married,Craft-repair,Own-child,White,0.0,0.0,1719.0,30.0,United-States
21,21,34.0,Private,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,0.0,5178.0,0.0,55.0,United-States
22,22,43.0,Private,Bachelors,13.0,Married-civ-spouse,Adm-clerical,Husband,White,0.0,0.0,0.0,40.0,United-States
23,23,27.0,Private,HS-grad,9.0,Never-married,Handlers-cleaners,Own-child,White,1.0,0.0,0.0,40.0,United-States
24,24,32.0,State-gov,Bachelors,13.0,Married-civ-spouse,Protective-serv,Husband,White,0.0,0.0,1887.0,45.0,United-States
25,25,30.0,Private,Assoc-voc,11.0,Married-civ-spouse,Prof-specialty,Husband,White,0.0,0.0,0.0,40.0,United-States
26,26,27.0,Private,Some-college,10.0,Never-married,Handlers-cleaners,Not-in-family,Black,0.0,0.0,0.0,50.0,United-States
27,27,54.0,Private,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,0.0,0.0,0.0,40.0,United-States
28,28,23.0,Private,HS-grad,9.0,Never-married,Priv-house-serv,Own-child,White,0.0,0.0,0.0,40.0,United-States
29,29,30.0,Private,HS-grad,9.0,Never-married,Other-service,Unmarried,White,1.0,0.0,0.0,40.0,United-States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45192,45192,39.0,Private,Some-college,10.0,Divorced,Adm-clerical,Unmarried,White,1.0,0.0,0.0,38.0,United-States
45193,45193,30.0,Private,Masters,14.0,Never-married,Prof-specialty,Not-in-family,White,0.0,0.0,0.0,40.0,Ireland
45194,45194,37.0,Private,HS-grad,9.0,Never-married,Tech-support,Not-in-family,White,1.0,14084.0,0.0,35.0,United-States
45195,45195,30.0,Private,HS-grad,9.0,Divorced,Other-service,Unmarried,White,1.0,0.0,0.0,40.0,United-States
45196,45196,27.0,Self-emp-inc,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,0.0,0.0,1740.0,40.0,United-States
45197,45197,21.0,Private,Some-college,10.0,Never-married,Adm-clerical,Not-in-family,White,1.0,0.0,0.0,40.0,United-States
45198,45198,20.0,Private,Some-college,10.0,Never-married,Farming-fishing,Not-in-family,White,1.0,0.0,0.0,40.0,United-States
45199,45199,23.0,Private,HS-grad,9.0,Never-married,Other-service,Own-child,White,0.0,0.0,0.0,35.0,United-States
45200,45200,48.0,Private,Bachelors,13.0,Divorced,Adm-clerical,Not-in-family,White,0.0,0.0,0.0,40.0,United-States
45201,45201,26.0,State-gov,Bachelors,13.0,Never-married,Exec-managerial,Not-in-family,White,1.0,0.0,0.0,35.0,United-States
45202,45202,48.0,Self-emp-not-inc,Assoc-voc,11.0,Married-civ-spouse,Other-service,Wife,White,1.0,0.0,0.0,15.0,United-States
45203,45203,26.0,Private,Bachelors,13.0,Never-married,Adm-clerical,Own-child,White,1.0,0.0,0.0,40.0,United-States
45204,45204,55.0,Self-emp-not-inc,Bachelors,13.0,Married-civ-spouse,Exec-managerial,Husband,White,0.0,0.0,0.0,40.0,United-States
45205,45205,40.0,Private,Prof-school,15.0,Married-civ-spouse,Exec-managerial,Husband,White,0.0,0.0,0.0,50.0,United-States
45206,45206,47.0,Private,Assoc-voc,11.0,Married-civ-spouse,Exec-managerial,Husband,White,0.0,15024.0,0.0,50.0,United-States
45207,45207,20.0,Private,Some-college,10.0,Never-married,Adm-clerical,Own-child,White,1.0,0.0,0.0,35.0,United-States
45208,45208,45.0,Private,Assoc-acdm,12.0,Divorced,Transport-moving,Not-in-family,White,0.0,0.0,0.0,55.0,United-States
45209,45209,31.0,State-gov,HS-grad,9.0,Never-married,Protective-serv,Other-relative,Asian-Pac-Islander,0.0,0.0,0.0,40.0,United-States
45210,45210,22.0,Private,Some-college,10.0,Never-married,Other-service,Not-in-family,White,0.0,0.0,0.0,40.0,United-States
45211,45211,40.0,Private,HS-grad,9.0,Divorced,Adm-clerical,Unmarried,Black,1.0,0.0,625.0,40.0,United-States
45212,45212,25.0,Private,HS-grad,9.0,Never-married,Adm-clerical,Own-child,White,1.0,0.0,0.0,40.0,United-States
45213,45213,23.0,Local-gov,HS-grad,9.0,Never-married,Other-service,Own-child,White,1.0,0.0,0.0,45.0,United-States
45214,45214,42.0,Local-gov,Some-college,10.0,Married-civ-spouse,Protective-serv,Husband,White,0.0,0.0,0.0,52.0,United-States
45215,45215,53.0,Private,HS-grad,9.0,Married-civ-spouse,Craft-repair,Husband,White,0.0,0.0,0.0,40.0,United-States
45216,45216,38.0,Private,Some-college,10.0,Married-civ-spouse,Exec-managerial,Husband,White,0.0,0.0,0.0,40.0,United-States
45217,45217,17.0,Private,11th,7.0,Never-married,Other-service,Own-child,White,0.0,0.0,0.0,15.0,United-States
45218,45218,50.0,Federal-gov,Some-college,10.0,Never-married,Adm-clerical,Not-in-family,White,0.0,0.0,0.0,40.0,United-States
45219,45219,17.0,Self-emp-inc,12th,8.0,Never-married,Adm-clerical,Own-child,White,1.0,0.0,0.0,16.0,United-States
45220,45220,38.0,Private,Bachelors,13.0,Married-civ-spouse,Prof-specialty,Husband,White,0.0,7688.0,0.0,40.0,United-States
45221,45221,22.0,Private,Some-college,10.0,Never-married,Farming-fishing,Own-child,White,0.0,0.0,0.0,10.0,United-States

In [24]:
# compare the column names in data & test this is the real data CSV
list(data.columns.values)

['age',
 'workclass',
 'education_level',
 'education-num',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'capital-gain',
 'capital-loss',
 'hours-per-week',
 'native-country',
 'income']

In [25]:
#List of column names in the test CSV
list(test.columns.values)

['Unnamed: 0',
 'age',
 'workclass',
 'education_level',
 'education-num',
 'marital-status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'capital-gain',
 'capital-loss',
 'hours-per-week',
 'native-country']

In [26]:
#making a box plot to show any outliers in the test data so we can get rid of it. 
#we're specifically looking for outliers in the "capital-gain" and "capital-loss" columns
#because they're skewing that data

# seaborn.boxplot(x=test['capital-gain'])
#Nevermind, i apparently don't have seaborn anymore, ugh.

In [28]:
#trying to get rid of outliers here?
#def reject_outliers(test, m=2):
#    return data[abs(data - np.mean(data)) < m * np.std(test)]

In [29]:
# Begin linear regression
# Assign the data to X and y

X = test[["education-num", "sex"]]
y = test["age"].values.reshape(-1, 1)
print(X.shape, y.shape)

(45222, 2) (45222, 1)

In [30]:
 # Use train_test_split to create training and testing data

### BEGIN SOLUTION
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

### END SOLUTION

In [31]:
# Create the model using LinearRegression

### BEGIN SOLUTION
from sklearn.linear_model import LinearRegression
model = LinearRegression()
### END SOLUTION

In [32]:
# Fit the model to the training data and calculate the scores for the training and testing data

### BEGIN SOLUTION
model.fit(X_train, y_train)
training_score = model.score(X_train, y_train)
testing_score = model.score(X_test, y_test)

### END SOLUTION 

print(f"Training Score: {training_score}")
print(f"Testing Score: {testing_score}")

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').